---
title: "Untitled"
author: "Bowei Kang"
date: "2025-06-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(mvtnorm)
library(LaplacesDemon)
library(dirmult)
library(invgamma)
library(MendelianRandomization)
library(Rcpp)
library(tictoc)
```

# load R script and functions

```{r}
source("/Users/fengsihao/Desktop/Dr.Chen/sihao/dgm6.R")
source("/Users/fengsihao/Desktop/Dr.Chen/sihao/init_setup_memo.R")
source("/Users/fengsihao/Desktop/Dr.Chen/sihao/init_setup_semo.R")
source("/Users/fengsihao/Desktop/Dr.Chen/sihao/init_setup_seso.R")
Rcpp::sourceCpp("/Users/fengsihao/Desktop/Dr.Chen/sihao/gibbs_joint_rcpp_nopr_pp_bound.cpp")
Rcpp::sourceCpp("/Users/fengsihao/Desktop/Dr.Chen/sihao/gibbs_seso_nohp.cpp")
Rcpp::sourceCpp("/Users/fengsihao/Desktop/Dr.Chen/sihao/gibbs_seso_uhp_only.cpp")
Rcpp::sourceCpp("/Users/fengsihao/Desktop/Dr.Chen/sihao/gibbs_semo_uhp_only_bound.cpp")
Rcpp::sourceCpp("/Users/fengsihao/Desktop/Dr.Chen/sihao/fastlm.cpp")

bern_prob <- function(rho, p, q) {
p00 = rho * sqrt(p*q*(1-p)*(1-q)) + (1-p)*(1-q)
p10 = 1 - q - p00
p01 = 1 - p - p00
p11 = p + q + p00 -  1
p00 = max(0, p00); p10 = max(0, p10); p01 = max(0, p01); p11 = max(0, p11)
return(c(p00, p01, p10, p11))
}
```

# sim

```{r}
out = NULL
nrep = 100
for (ii in 1:nrep) {
# ii=2000+ii
set.seed(ii)
print(ii)
if (ii %% 100 == 0) message(ii)
# parameters
m = 200
nx1 = 20000; nx2 = 80000
ny1 = 20000; ny2 = 80000
a_gamma1 = -0.3; b_gamma1 = 0.3; a_gamma2 = -0.3; b_gamma2 = 0.3
rho_gamma = 0.6
a_f = 0.1; b_f = 0.3 
a_alpha1 = -0.1; b_alpha1 = 0.1; a_alpha2 = -0.1; b_alpha2 = 0.1
rho_alpha = 0.6
a_phi1 = -0.1; b_phi1 = 0.1; a_phi2 = -0.1; b_phi2 = 0.1
rho_eta = 0.9
# error_sd_exp = 1
theta1 = 0; theta2 = 0
q_uhp1 = 1; q_uhp2 = 1
q_chp1 = 0.1; q_chp2 = 0.1
p_cutoff = 1e-5
a_prior = 5
# generate summary statistics
GWAS_summary = dgm6(m, nx1, nx2, ny1, ny2, a_gamma1, b_gamma1, a_gamma2, b_gamma2, rho_gamma, a_f, b_f, a_alpha1, b_alpha1, a_alpha2, b_alpha2, rho_alpha, a_phi1, b_phi1, a_phi2, b_phi2, rho_eta, theta1, theta2, q_uhp1, q_uhp2, q_chp1, q_chp2, beta_XU=1, beta_YU=1)
GWAS_summary$h2_exposure1; GWAS_summary$h2_exposure2
GWAS_summary$h2_causal1; GWAS_summary$h2_causal2
GWAS_summary$h2_uhp1; GWAS_summary$h2_uhp2
GWAS_summary$h2_chp1; GWAS_summary$h2_chp2
# select IV
b_exp_1_raw = c(GWAS_summary$b_exp_1)
b_exp_2_raw = c(GWAS_summary$b_exp_2)
b_out_1_raw = c(GWAS_summary$b_out_1)
b_out_2_raw = c(GWAS_summary$b_out_2)
se_exp_1_raw = c(GWAS_summary$se_exp_1)
se_exp_2_raw = c(GWAS_summary$se_exp_2)
se_out_1_raw = c(GWAS_summary$se_out_1)
se_out_2_raw = c(GWAS_summary$se_out_2)
z_gamma_1 = abs(b_exp_1_raw) / se_exp_1_raw
z_gamma_2 = abs(b_exp_2_raw) / se_exp_2_raw
p_gamma_1 = 2*(1 - pnorm(z_gamma_1))
p_gamma_2 = 2*(1 - pnorm(z_gamma_2))
iv_keep_1 = p_gamma_1 < p_cutoff
iv_keep_2 = p_gamma_2 < p_cutoff
K1 = sum(iv_keep_1)
K2 = sum(iv_keep_2)
iv_keep = iv_keep_1 | iv_keep_2
K = sum(iv_keep)

if (K>=5) {
# get summary statistics after selection
b_out_1s = b_out_1_raw[iv_keep_1]; se_out_1s = se_out_1_raw[iv_keep_1]
b_exp_1s = b_exp_1_raw[iv_keep_1]; se_exp_1s = se_exp_1_raw[iv_keep_1]
b_out_2s = b_out_2_raw[iv_keep_2]; se_out_2s = se_out_2_raw[iv_keep_2]
b_exp_2s = b_exp_2_raw[iv_keep_2]; se_exp_2s = se_exp_2_raw[iv_keep_2]
b_out_1 = b_out_1_raw[iv_keep]; se_out_1 = se_out_1_raw[iv_keep]
b_exp_1 = b_exp_1_raw[iv_keep]; se_exp_1 = se_exp_1_raw[iv_keep]
b_out_2 = b_out_2_raw[iv_keep]; se_out_2 = se_out_2_raw[iv_keep]
b_exp_2 = b_exp_2_raw[iv_keep]; se_exp_2 = se_exp_2_raw[iv_keep]

# run MR
# FusioMRs empirical (outcome 1, smaller population)
niter = 20000
# hyper parameters
a_gamma_prior = a_theta_prior = max(a_prior, K/4)
# use all SNPs before pval thresholding
b_gamma_prior = max(1e-3, (var(b_exp_1_raw) - mean(se_exp_1_raw)^2)) * (a_gamma_prior-1)
b_theta_prior = max(1e-6, (var(b_out_1_raw) - mean(se_out_1_raw)^2)) * (a_theta_prior-1)
a_q_prior = b_q_prior = 1


# starting values
#start_val = init_setup(niter, K1, alpha_init = 1, beta_init = theta1, sigma_gamma_init = 0.1, sigma_theta_init = 0.1, q_init = 0) 
# rcpp
#res1 = gibbs_rcpp_nopr(niter, K1, beta_tk = start_val$beta_tk, alpha_tk = start_val$alpha_tk, eta_tk = start_val$eta_tk, theta_tk = start_val$theta_tk, gamma_tk = start_val$gamma_tk, q_tk = start_val$q_tk, b_out_1s, b_exp_1s, (se_out_1s)^2, (se_exp_1s)^2, sigma2_gamma_tk = start_val$sigma2_gamma_tk, sigma2_theta_tk = start_val$sigma2_theta_tk, a_gamma_prior, b_gamma_prior, a_theta_prior, b_theta_prior, a_q_prior, b_q_prior) 

# starting values
start_val = init_setup(niter, K, alpha_init = 1, beta_init = theta, sigma_gamma_init = 0.1, sigma_theta_init = 0.1)
# rcpp
res2 = gibbs_seso_uhp_only_cpp(
niter, K, start_val$beta_tk, start_val$theta_tk, start_val$gamma_tk,
start_val$sigma2_gamma_tk, start_val$sigma2_theta_tk,
b_out, b_exp, (se_out)^2, (se_exp)^2,
a_gamma_prior, b_gamma_prior, a_theta_prior, b_theta_prior
)

ids = (niter/2 + 1):niter
post_flip = label_flip(niter, res1, rep(0, K1))
bhat_s1 = post_flip$b_mean
se_bhat_s1 = post_flip$b_sd
bci_s1 = post_flip$bci

# FusioMRm
niter = 20000
# hyper parameters
# use all SNPs before pval thresholding
m_gamma = m_theta = max(a_prior, K/2)
sigma2_gamma_prior_mean_1 = max(1e-3, (var(b_exp_1_raw) - mean(se_exp_1_raw)^2))
sigma2_gamma_prior_mean_2 = max(1e-3, (var(b_exp_2_raw) - mean(se_exp_2_raw)^2))
sigma2_theta_prior_mean_1 = max(1e-6, (var(b_out_1_raw) - mean(se_out_1_raw)^2))
sigma2_theta_prior_mean_2 = max(1e-6, (var(b_out_2_raw) - mean(se_out_2_raw)^2))
Sigma_gamma_init = diag(c(sigma2_gamma_prior_mean_1, sigma2_gamma_prior_mean_2))
Sigma_theta_init = diag(c(sigma2_theta_prior_mean_1, sigma2_theta_prior_mean_2))
V_gamma = Sigma_gamma_init * (m_gamma - 3)
V_theta = Sigma_theta_init * (m_theta - 3)
pst_init = bern_prob(rho_eta, q_chp1, q_chp2)
cc = rep(1, 4) # Dirichlet parameters
# starting values
start_val = init_setup_memo(niter, K, alpha_1_init = 1, alpha_2_init = 1, beta_1_init = theta1, beta_2_init = theta2, eta_1_init = rep(0,K), eta_2_init = rep(0,K), pst_init = pst_init) 
# rcpp
res_memo = gibbs_joint_rcpp_nopr(niter, K, beta_1_tk = start_val$beta_1_tk, beta_2_tk = start_val$beta_2_tk, alpha_1_tk = start_val$alpha_1_tk, alpha_2_tk = start_val$alpha_2_tk, eta_1_tk = start_val$eta_1_tk, eta_2_tk = start_val$eta_2_tk, theta_1_tk = start_val$theta_1_tk, theta_2_tk = start_val$theta_2_tk, gamma_1_tk = start_val$gamma_1_tk, gamma_2_tk = start_val$gamma_2_tk, pst_tk = start_val$pst_tk, b_out_1, b_exp_1, (se_out_1)^2, (se_exp_1)^2, b_out_2, b_exp_2, (se_out_2)^2, (se_exp_2)^2, Sigma_gamma_init, Sigma_theta_init, m_gamma, V_gamma, m_theta, V_theta, cc) 
ids = (niter/2 + 1):niter
post_flip = label_flip_joint(niter, res_memo, rep(0,K), rep(0,K))
b1_memo = post_flip$b1_mean; se1_memo = post_flip$b1_sd
b2_memo = post_flip$b2_mean; se2_memo = post_flip$b2_sd
bci_1_memo = post_flip$bci1
bci_2_memo = post_flip$bci2
# sigma2_gamma1 = mean(res_memo$sigma2_gamma1_tk[ids], na.rm = T)
# sigma2_gamma2 = mean(res_memo$sigma2_gamma2_tk[ids], na.rm = T)
# sigma2_theta1 = mean(res_memo$sigma2_theta1_tk[ids], na.rm = T)
# sigma2_theta2 = mean(res_memo$sigma2_theta2_tk[ids], na.rm = T)

# competing methods (outcome 1)
mr.obj = MendelianRandomization::mr_input(bx = b_exp_1s, bxse = se_exp_1s, by = b_out_1s, byse = se_out_1s)
# IVW fixed
IVW_f = MendelianRandomization::mr_ivw(mr.obj, model = 'fixed')
b_ivw = IVW_f$Estimate; se_ivw = IVW_f$StdError
# MR-Egger
Egger = try(MendelianRandomization::mr_egger(mr.obj))
if(class(Egger) != 'try-error' & !is.null(Egger)) {
b_egger = Egger$Estimate; se_egger = Egger$StdError.Est
} else {b_egger = se_egger = NA}
# cML
cml = MendelianRandomization::mr_cML(mr.obj, MA = T, DP = F, num_pert = 200, n = nx1)
b_cml = cml$Estimate; se_cml = cml$StdError
# cML-DP
cml_dp = MendelianRandomization::mr_cML(mr.obj, MA = T, DP = T, num_pert = 200, n = nx1)
b_cml_dp = cml_dp$Estimate; se_cml_dp = cml_dp$StdError

# output
tmp = c(seed = ii, K = K, K1 = K1, K2 = K2, s2_gamma1_theo = (b_gamma1-a_gamma1)^2/12, s2_theta1_theo = (b_alpha1-a_alpha1)^2/12, s2_gamma1_emp = max(1e-3, (var(b_exp_1_raw) - mean(se_exp_1_raw)^2)), s2_theta1_emp = max(1e-6, (var(b_out_1_raw)-mean(se_out_1_raw^2))), fusiom_rej_b = bci_1_memo[2] < 0 | bci_1_memo[1] > 0, fusios_rej_b = bci_s1[2] < 0 | bci_s1[1] > 0, ivw = b_ivw + 1.96*se_ivw < 0 | b_ivw - 1.96*se_ivw > 0, egger = b_egger + 1.96*se_egger < 0 | b_egger - 1.96*se_egger > 0, cml = b_cml + 1.96*se_cml < 0 | b_cml - 1.96*se_cml > 0, cml_dp = b_cml_dp + 1.96*se_cml_dp < 0 | b_cml_dp - 1.96*se_cml_dp > 0)
out = rbind(out, tmp)
} # end if
} # end loop

# summarize
out = as.data.frame(out)
colnames(out) = c('seed', 'K', 'K1', 'K2', 's2_gamma1_theo', 's2_theta1_theo', 's2_gamma1_emp', 's2_theta1_emp', 'fusio_m', 'fusio_s', 'ivw', 'egger', 'cml', 'cml_dp')
colMeans(out, na.rm = TRUE)
nrow(out)
table(out$K)
```




